name: widgets
description: widget library
version: 1.0.0
homepage: https://github.com/flutter-packagist/widgets

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  easy_refresh: 3.3.2+1
  dio: 5.3.2
  network:
    path: ../network

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
