name: widgets
description: widget library
version: 1.0.1
homepage: https://github.com/flutter-packagist/widgets

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: 3.2.3   # 网络图片加载
  easy_refresh: 3.3.2+1         # 下拉刷新，上拉加载
  dio: 5.3.2                    # 网络请求
  network:
    git:
      url: https://github.com/flutter-packagist/network.git
      ref: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
